apiVersion: kustomize.config.k8s.io/v1beta1
namespace: mealie
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
 # - secret.yaml
  - deployment.yaml
  - pvc.yaml
  - service.yaml


