apiVersion: v1
kind: Secret
metadata:
  name: mealie-database-secret
  namespace: mealie
type: Opaque
data:
  POSTGRES_USER: bWVhbGll  # Base64 encoded value of "mealie"
  POSTGRES_PASSWORD: bWVhbGll  # Base64 encoded value of "mealie"